kind: pipeline
name: deployment

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: deploy
    image: docker/compose:1.23.2
    environment:
      MONGO_USER:
        from_secret: MONGO_USER
      MONGO_PASSWORD:
        from_secret: MONGO_PASSWORD
      MONGO_DB:
        from_secret: MONGO_DB
      JWT_SECRET_KEY:
        from_secret: JWT_SECRET_KEY
        
    commands:
      - COMPOSE_PROJECT_NAME=homepage docker-compose up -d --build
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock