version: "3.5"

services:
  frontend:
    container_name: tilas_frontend
    build:
      context: frontend/

  db:
    container_name: tilas_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - ./backend/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  backend:
    container_name: tilas_backend
    links:
      - db
    build:
      context: backend/
    environment:
      PORT: 80
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOST: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@db:27017/${MONGO_DB}

  homepage:
    container_name: homepage
    build:
      context: ./
    links:
      - frontend
      - backend
    restart: unless-stopped

networks:
  default:
    external:
      name: homenet
