FROM node:alpine AS builder

RUN mkdir -p /opt/app
RUN apk add --no-cache libc6-compat
ENV NODE_ENV production
ENV PUBLIC_PATH /storybook/

WORKDIR /opt/app
COPY . /opt/app

RUN npm --production=false install && npm run storybook:build

FROM nginx
COPY --from=builder /opt/app/storybook/ /usr/share/nginx/html