FROM node:alpine

RUN mkdir -p /opt/app
RUN apk add --no-cache libc6-compat
ENV NODE_ENV production
ENV PORT 3000
EXPOSE 3000

COPY . /opt/app
WORKDIR /opt/app

RUN apk --no-cache --virtual build-dependencies add \
    python \
    make \
    g++

RUN yarn --production=false install
RUN yarn workspace @devtail/frontend install --production=false
RUN yarn workspace @devtail/frontend run build
RUN apk del build-dependencies

CMD [ "yarn", "workspace", "@devtail/frontend", "run" "start" ]