version: "3.5"

services:
  frontend:
    container_name: tilas_frontend
    build:
      context: frontend/

  db:
    container_name: tilas_db
    image: mongo
    restart: always
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSOWRD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
    volumes:
      - backend/mongo-init.local.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    container_name: tilas_backend
    links:
      - db
    build:
      context: backend/
    environment:
      PORT: 80
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOST: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@db:27017/${MONGO_DB}

  homepage:
    container_name: homepage
    build:
      context: ./
    links:
      - frontend
      - backend
    volumes:
      - ${BASE_DIR}/caddy:/root/.caddy
    restart: unless-stopped

networks:
  default:
    external:
      name: homenet
