version: "3.5"

services:
  nextjs:
    container_name: nextjs
    build:
      context: docker/nextjs

  ghost_db:
    image: mysql:5.7
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_DB_PASSWORD}
    volumes:
      - ${BASE_DIR}/ghost_db/mysql:/var/lib/mysql

  ghost:
    container_name: ghost
    image: ghost:latest
    restart: always
    links:
      - ghost_db
    depends_on:
      - ghost_db
    environment:
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: root
      database__connection__password: ${GHOST_DB_PASSWORD}
      database__connection__database: ghost
    volumes:
      - ${BASE_DIR}/ghost_content:/var/lib/ghost/content

  storybook:
    container_name: storybook
    build:
      context: docker/storybook
    restart: always
  
  homepage:
    container_name: homepage
    build:
      context: docker/caddy
    links:
      - ghost_frontend
      - ghost_backend
      - framework_storybook
    volumes:
      - ${BASE_DIR}/caddy:/root/.caddy
    restart: unless-stopped

networks:
  default:
    external:
      name: homenet
