version: "3.5"

services:
  ghost_frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      BASE_URL: https://ghost.thenairn.com
    container_name: ghost_frontend

  ghost_db:
    image: mysql:5.7
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_DB_PASSWORD}
    volumes:
      - ${BASE_DIR}/ghost_db/mysql:/var/lib/mysql

  ghost_backend:
    container_name: ghost_backend
    image: ghost:latest
    restart: always
    links:
      - ghost_db
    depends_on:
      - ghost_db
    environment:
      url: https://ghost.thenairn.com
      database__client: mysql
      database__connection__host: ghost_db
      database__connection__user: root
      database__connection__password: ${GHOST_DB_PASSWORD}
      database__connection__database: ghost
    volumes:
      - ${BASE_DIR}/ghost_content:/var/lib/ghost/content

  framework_storybook:
    container_name: framework_storybook
    build:
      context: ./
      dockerfile: ./storybook.Dockerfile
    restart: always

networks:
  default:
    external:
      name: homenet
