version: "3.5"

services:
  frontend:
    container_name: tilas_frontend
    build:
      context: frontend/

  backend:
    container_name: tilas_backend
    build:
      context: backend/
    environment:
      PORT: 80
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DB_HOST: ${DB_HOST}

  homepage:
    container_name: homepage
    build:
      context: ./
    links:
      - frontend
      - backend
    restart: unless-stopped

networks:
  default:
    external:
      name: homenet
