kind: pipeline
name: deployment

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: deploy
    image: docker/compose:1.23.2
    environment:
      GHOST_DB_PASSWORD:
        from_secret: GHOST_DB_PASSWORD
    commands:
      - COMPOSE_PROJECT_NAME=homepage docker-compose up -d --build
    volumes:
      - name: dockersock
        path: /var/run/docker.sock

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock