version: "3.5"

services:

  tilas_db:
    container_name: tilas_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${TILAS_DB_PASSWORD}

  ghost_db:
    image: mysql:5.7
    container_name: ghost_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${GHOST_DB_PASSWORD}
    volumes:
      - ${BASE_DIR}/ghost_db/mysql:/var/lib/mysql


networks:
  default:
    external:
      name: homenet
